aws:
  hosts:
    sorrowset-vm-1:
      ansible_host: <<OUTPUT FROM TERRAFORM>>

      hostname: "sorrowset-vm-1"
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: "/home/<<USERNAME>>/.ssh/ansiblekey"
      ansible_ssh_public_key_file: "/home/<<USERNAME>>/.ssh/ansiblekey.pub"
      ansible_ssh_user: 'ansible'

      # Create Users
      users:
        - username: mellonaut
          name: HauntedMound
          authorized_keys:
            - "{{ lookup('file', '/home/<<USERNAME>>/.ssh/ansiblekey.pub') }}"
            # - "https://github.com/<<USERNAME>>.keys"
          home_create: yes
          append: yes
          home_mode: "0750"
          shell: '/usr/bin/zsh'
      
      users_authorized_keys_exclusive: yes
      security_sudoers_passwordless:
        - mellonaut

      # ZSH Settings
      zsh_shared: yes
      
      # Docker Settings
      dockernet: "docker"
      docker_home_dir: '/opt/docker'

      # Pip Settings
      pip_install_packages:
        - name: docker
      pip_executable: pip3
      pip_package: python3-pip

      # NTP
      ntp_timezone: 'America/New_York'
